version: "2"
prepare:
  fetch:
    - "https://raw.githubusercontent.com/internetee/style-guide/master/.rubocop-ruby.yml"
    - url: "https://raw.githubusercontent.com/internetee/style-guide/master/.rubocop-rails.yml"
      path: ".rubocop.yml"
plugins:
  brakeman:
    enabled: true
    checks:
      sql_injection:
        enabled: false
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
  eslint:
    enabled: true
    channel: eslint-5
  fixme:
    enabled: true
  rubocop:
    enabled: true
    channel: rubocop-0-74
    checks:
      Rubocop/Metrics/BlockLength:
        enabled: false
      Rubocop/Bundler/OrderedGems:
        enabled: false
exclude_patterns:
  - "app/models/audit/"
  - "app/models/version/"
  - "app/models/concerns/versions.rb"
  - "bin/"
  - "config/"
  - "db/"
  - "lib/core_monkey_patches/"
  - "lib/daemons/"
  - "lib/gem_monkey_patches/"
  - "lib/tasks/api_log.rake"
  - "lib/tasks/bootstrap.rake"
  - "lib/tasks/db.rake"
  - "lib/tasks/documents.rake"
  - "lib/tasks/legal_doc.rake"
  - "lib/tasks/whois.rake"
  - "test/"
  - "vendor/"
  - "CHANGELOG.md"
